import { Environment, OrbitControls } from "@react-three/drei";
import { Canvas } from "@react-three/fiber";
import Scene from "src/components/3d/scene";
import Display from "src/components/dom/display";
import NavBar from "src/components/dom/navbar";
import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Dazzling Donuts</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main className="w-screen overflow-hidden bg-slate-100 selection:bg-rose-950 selection:text-slate-200">
        <div className="relative z-20 h-screen pointer-events-none">
          <NavBar />
          <div className="flex h-full flex-col items-center justify-center gap-4">
            <Display />
            <button className="btn">Buy Donuts</button>
            <button className="btn">Make A Donut</button>

            
          </div>
        </div>

        <div className="fixed left-0 top-0 h-screen w-screen">
          <Canvas className="bg-slate-900">
            <Scene />
            <Environment preset="studio"/>
            <OrbitControls />
          </Canvas>
        </div>
      </main>
    </>
  );
}
